# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_snipcartsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productAt',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
